version: '3.8'

services:
  prism-mock:
    image: stoplight/prism:4
    container_name: library_prism_mock
    ports:
      - "4010:4010"
    volumes:
      - ./openapi.yaml:/tmp/openapi.yaml:ro
    command: >
      mock 
      --host 0.0.0.0 
      --port 4010 
      --dynamic 
      --cors 
      /tmp/openapi.yaml
    restart: unless-stopped
    networks:
      - prism_network

networks:
  prism_network:
    driver: bridge